SELECT OUTS.ANIMAL_ID, OUTS.NAME FROM ANIMAL_OUTS OUTS  -- ¨Í
LEFT JOIN ANIMAL_INS INS  --  ¨Î
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID  --  ¨Ï
WHERE INS.ANIMAL_ID IS NULL  --  ¨Ð
ORDER BY OUTS.ANIMAL_ID  --  ¨Ñ